### ISSUE TITLE
How to train

### ISSUE THREAD

**Issue by citymonkeymao** [axium/CNN-For-End-to-End-Deblurring#1]
Can you also share the training code? Did you used GAN to train the network or just use clean pictures as the output?

**Comment by axium** [comment]
Training is easy to do from here. I created blurry images from clean celebA images and simply trained with blurry as input and clean as output.  You need to do the same. Setup X_blurry and X_clean.  Then:

deblur_CNN.fit( X_blurry,  X_clean )

Also, for good results, make sure to set the filter size of the first layer to blur kernel size.

**Comment by citymonkeymao** [comment]
Got it, thanks!
How many pictures did you used in celebA training?
The [pix2pix paper](https://arxiv.org/pdf/1611.07004.pdf) report that directly train network with L1 loss would result in blured output, but results from this network was really good!

**Comment by axium** [comment]
Sorry for the late response. I created 150, 000 blurry and clean images on which I did my training.

**Comment by citymonkeymao** [comment]
Thanks!
