### ISSUE TITLE
Intuition behind a loop

### ISSUE THREAD

**Issue by sanelec1989** [axium/CNN-For-End-to-End-Deblurring#2]
why the output of the third convolution layer fed back to input layer ?

deblur_CNN_layer3 = Conv2D(filters=320, kernel_size=1, strides = 1, padding='same')(deblur_CNN_layer2)
deblur_CNN_layer1 = BatchNormalization()(deblur_CNN_layer3)
deblur_CNN_layer1 = Activation('relu')(deblur_CNN_layer3)

**Comment by axium** [comment]
Its a typo.
