### ISSUE TITLE
Someting about training

### ISSUE THREAD

**Issue by JackyWang-001** [axium/CNN-For-End-to-End-Deblurring#4]
Thanks for your wonderful work. I write the training code based on your network. Here are my problems.
(1) I want to train the network with input 128*128，then what should I do with the network ?
(2) It seems that the 'mean_squared_error' you use is the same with the 'perceptual_loss' mentioned in DeblurGAN. Is it right?
(3) It seems that the weight you train using the typo network. Because when I correct the network，the weight does not work.
Expect for your reply!
Thanks again!

**Comment by axium** [comment]
(1) Just change the input shape. But since this is fully convolutional network, you can also feed 128x128 images, without any retraining.
(2) No. Perceptual Loss is totally different from mean squared error.
(3) You should re-train the network after fixing the typo.

**Comment by JackyWang-001** [comment]
@axium Thank you very much!
Long live China-Pakistan friendship!
