### ISSUE TITLE
how to generate blury images?

### ISSUE THREAD

**Issue by liang23333** [axium/CNN-For-End-to-End-Deblurring#5]
hello, can you share your code about how to generate blury images from sharp images ?

**Comment by axium** [comment]
It pretty simple. You just use some kernel, generated synthetically, or using some real world blur sets. Just convolve images with these blurs and you will get blurry images.

**Comment by liang23333** [comment]
Thank you!

> It pretty simple. You just use some kernel, generated synthetically, or using some real world blur sets. Just convolve images with these blurs and you will get blurry images.

Thank you!
